local UserNameLine = "[*]: let's play a game.. " .. game.Players.LocalPlayer.Name .. "\n"

rconsoleprint('@@RED@@')
rconsolename("Hello " .. game.Players.LocalPlayer.Name .. " :)")
rconsolewarn("are you scared...?")
wait(3)
rconsolewarn("do you want forgiveness..?")
wait(3)
rconsoleprint('@@RED@@')
rconsoleprint("[*]: Maybe you want death.. who knows..\n")
wait(3)
rconsoleprint('@@GREEN@@')
rconsoleprint(UserNameLine)
wait(.5)
rconsoleprint('@@GREEN@@')
rconsoleprint("[*]: ...\n")
wait(.5)
rconsoleprint('@@GREEN@@')
rconsoleprint("[*]: You'll enjoy it, dont worry!\n")
wait(2)
rconsoleprint('@@CYAN@@')
rconsoleprint("[*]: It's called... Bye bye.. \n")
wait(1)
game:Shutdown()
